#!/bin/bash

name=0
typ=0
exe=0
args=""
path=/home/sean/61b

for f in $*
do
    case $f in 
	(-name) name=1;;
	(-type) typ=1;;
	(-exec) exe=1;;
    esac
    args=($f ${args[*]})
done

function set_nIndex {
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	if [[ "${args[$i]}" == "-name" ]]; then
	    nIndex=$i
	    break
	fi
    done
}

function set_tIndex {
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	if [[ "${args[$i]}" == "-type" ]]; then
	    tIndex=$i
	    break
	fi
    done
}

function set_eIndex {
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	if [[ "${args[$i]}" == "-exec" ]]; then
	    eIndex=$i
	    break
	fi
    done
}

function print_args {
    echo "args array"
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	echo "${args[$i]}"
    done
}

function check_type {
    if [[ "${args[tIndex-1]}" == "f"  ]]; then
	if [[ ! -f $f ]]; then
	    print=0	    
	fi
    else
	if [[ ! -d $f ]]; then
	    continue
	fi 
    fi
}

function get_fname {
    fname=$(basename $f)   
}

function check_name {
    compWrd="${args[$nIndex - 1]}"
    if [[ "$compWrd" == *"*"* ]]; then
	echo "wildcard found"
    elif [[ "$name" == 1 && $f != "$path/$compWrd" ]]; then
	continue
    fi

}

set_nIndex
set_tIndex
set_eIndex


function search_dir {
    for f in "$path"/*
    do
	print=1
	get_fname
	if [[ $name == 1 ]] ; then
		check_name
	fi
	if [[ $typ == 1 ]]; then
		check_type
	fi
	if [[ "$print" == 1 ]]; then
	    echo $f
	fi
	if [[ "$exe" == 1  ]]; then
	    echo "exec cmd on $f"
	fi
	if [[ -d $f  ]]; then
	    origPath=$path
	    path="$f"
	    search_dir
	    path=$origPath
	
	fi
    done
}


search_dir
