#!/bin/bash

name=0
typ=0
print=0
exe=0
args=""
path=/home/sean/61b

for f in $*
do
    case $f in 
	(-name) name=1;;
	(-type) typ=1;;
	(-exec) exe=1;;
    esac
    args=($f ${args[*]})
done

function get_path {
    numArgs="${#args[@]}"
    echo "size of args: $numArgs"
    path="${args[$numArgs-1]}"
}

function set_nIndex {
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	if [[ "${args[$i]}" == "-name" ]]; then
	    nIndex=$i
	    break
	fi
    done
}

function set_tIndex {
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	if [[ "${args[$i]}" == "-type" ]]; then
	    tIndex=$i
	    break
	fi
    done
}
function set_eIndex {
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	if [[ "${args[$i]}" == "-exec" ]]; then
	    eIndex=$i
	    break
	fi
    done
}
function print_args {
    echo "args array"
    arrLen=${#args[@]}
    for ((i=0; i < arrLen; ++i));
    do
	echo "${args[$i]}"
    done
}

function index_test {
    echo "index test"
    echo "name $name index $nIndex with arg of ${args[$nIndex-1]}"
    echo "type  $typ index $tIndex with arg of ${args[$tIndex-1]}"
    echo "print $print"
    echo "exe $exe index $eIndex"
}

function check_type {
    if [[ "${args[tIndex-1]}" == "f"  ]]; then
	if [[ ! -f $f ]]; then
	    print=0	    
	fi
    else
	if [[ ! -d $f ]]; then
	    continue
	fi 
    fi
}
function remove_wildcard {
    cmpWrd=""
    wrdLen=${#compWrd}
    for ((i=0;i<wrdLen;++i));
    do
	char="${compWrd:$i:1}"
	if [[ $char != '*'  ]]; then
	    cmpWrd+=$char
	fi
    done
}
function get_fname {
    fname=$(basename $f)   
}
function check_name {
    compWrd="${args[$nIndex - 1]}"
    if [[ "$compWrd" == *"*"* ]]; then
	echo "wildcard found"
    elif [[ "$name" == 1 && $f != "$path/$compWrd" ]]; then
	echo "$f != $path/$compWrd"
	continue
    fi

}

set_nIndex
set_tIndex
set_eIndex


function search_dir {
    for f in "$path"/*
    do
	print=1
	get_fname
	if [[ $name == 1 ]] ; then
		check_name
	elif [[ $typ == 1 ]]; then
		check_type
	fi
	if [[ "$print" == 1 ]]; then
	    echo $f
	fi
	if [[ -d $f  ]]; then
	    origPath=$path
	    path="$f"
	    search_dir
	    path=$origPath
	
	fi
    done
}

#get_path
search_dir
